services:
  web:
    build:
      context: .
      dockerfile: ./Docker/Web.Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-}
        VITE_AUTH_WORKER_URL: ${VITE_AUTH_WORKER_URL:-}
    container_name: study-helper-web
    restart: unless-stopped
    ports:
      - "${VITE_PORT:-5180}:80"

  web-dev:
    build:
      context: .
      dockerfile: ./Docker/Web.Dockerfile.dev
    container_name: study-helper-web-dev
    restart: unless-stopped
    ports:
      - "${VITE_PORT:-5180}:${VITE_PORT:-5180}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
