server {
    listen 80;
    server_name localhost;

    client_max_body_size 2G;

    location /stats/ {
        return 204;
    }

    location = /index.html {
        root /app/web;
        add_header Cache-Control "no-cache";
    }

    location /assets/ {
        root /app/web;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        root /app/web;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
